spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    hibernate:
        ddl-auto: none
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todoapp
    driverClassName: com.mysql.cj.jdbc.Driver
    username: jade
    password: jade
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:h2:mem:todoapp
#    driverClassName: org.h2.Driver
#    username: jade
#    password: jade
#  h2:
#    console:
#      enabled: true
